import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import DataTable from '@/components/DataTable'
import TurnSentence from '@/components/TurnSentence'
import DeleteLastWord from '@/components/DeleteLastWord'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <DataTable></DataTable>
        <br></br>
        <br></br>
        <TurnSentence></TurnSentence>
        <br></br>
        <br></br>
        <DeleteLastWord></DeleteLastWord>
      </main>
    </>
  )
}
